name: Build and Release JAR

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build with Maven
        run: mvn -DskipTests clean package

      - name: Create GitHub Release and upload JAR
        uses: ncipollo/release-action@v1
        with:
          tag: v1.0
          release_name: v1.0
          files: target/*.jar
